//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNewsModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_location
    {
        public int category_location_id { get; set; }
        public int location_id { get; set; }
        public int category_id { get; set; }
        public Nullable<int> sub_category_id { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.DateTime> logical_delete_date { get; set; }
    
        public virtual category category { get; set; }
        public virtual sub_category sub_category { get; set; }
        public virtual location location { get; set; }
    }
}
