//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNewsModel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITS_MobileNewsEntities : DbContext
    {
        public ITS_MobileNewsEntities()
            : base("name=ITS_MobileNewsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agency> agencies { get; set; }
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<application_agency> application_agency { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_location> category_location { get; set; }
        public virtual DbSet<category_news> category_news { get; set; }
        public virtual DbSet<category_service> category_service { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<service> services { get; set; }
        public virtual DbSet<service_icon> service_icon { get; set; }
        public virtual DbSet<sub_category> sub_category { get; set; }
    }
}
