//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNewsModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public news()
        {
            this.category_news = new HashSet<category_news>();
        }
    
        public int news_id { get; set; }
        public int agency_id { get; set; }
        public int language_id { get; set; }
        public string news_title { get; set; }
        public string news_content { get; set; }
        public byte[] news_image { get; set; }
        public Nullable<System.DateTime> publish_date { get; set; }
        public string archive_flag { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.DateTime> logical_delete_date { get; set; }
    
        public virtual agency agency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category_news> category_news { get; set; }
        public virtual language language { get; set; }
    }
}
