//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileNewsModel.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_icon
    {
        public int service_icon_id { get; set; }
        public int service_id { get; set; }
        public byte[] service_image { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.DateTime> logical_delete_date { get; set; }
    
        public virtual service service { get; set; }
    }
}
